version: "3.8"
services:
  # ---------- Catalog ----------
  #  catalog-db:
  # image: postgres:15
  # container_name: catalog-db
  # restart: always
  # environment:
  #   POSTGRES_DB: catalogdb
  #   POSTGRES_USER: yash
  #   POSTGRES_PASSWORD: yash123
  # ports:
  #   - "5434:5432"
  # volumes:
  #   - catalog_data:/var/lib/postgresql/data
  #   - ./init/catalog:/docker-entrypoint-initdb.d

  #catalog-service:
  # build:
  #   context: ../catalog-service
  #   dockerfile: Dockerfile
  # container_name: catalog-service
  # depends_on:
  #   - catalog-db
  # ports:
  #   - "8080:8080"
  # environment:
  #   SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-db:5432/catalogdb
  #   SPRING_DATASOURCE_USERNAME: yash
  #   SPRING_DATASOURCE_PASSWORD: yash123
  #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #   SERVER_PORT: 8080

  # ---------- Inventory ----------
  #inventory-db:
  # image: postgres:15
  # container_name: inventory-db
  # restart: always
  # environment:
  #   POSTGRES_DB: inventorydb
  #   POSTGRES_USER: yash
  #   POSTGRES_PASSWORD: yash123
  # ports:
  #   - "5433:5432"
  # volumes:
  #   - inventory_data:/var/lib/postgresql/data
  #   - ./init/inventory:/docker-entrypoint-initdb.d

  #inventory-service:
  # build:
  #   context: ../inventory-service
  #   dockerfile: Dockerfile
  # container_name: inventory-service
  # depends_on:
  #   - inventory-db
  # ports:
  #   - "8081:8081"
  # environment:
  #   SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventorydb
  #   SPRING_DATASOURCE_USERNAME: yash
  #   SPRING_DATASOURCE_PASSWORD: yash123
  #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #   SERVER_PORT: 8081


  # ---------- Orders ----------
  #orders-db:
  # image: postgres:15
  # container_name: orders-db
  # restart: always
  # environment:
  #   POSTGRES_DB: ordersdb
  #   POSTGRES_USER: yash
  #   POSTGRES_PASSWORD: yash123
  # ports:
  #   - "5435:5432"
  # volumes:
  #   - orders_data:/var/lib/postgresql/data
  #   - ./init/orders:/docker-entrypoint-initdb.d
  # healthcheck:
  #   test: ["CMD-SHELL", "pg_isready -U yash -d ordersdb"]
  #   interval: 5s
  #   timeout: 5s
  #   retries: 10
  # networks:
  #   - eci-net

  #orders-service:
  # build:
  #   context: ../orders-service
  #   dockerfile: Dockerfile
  # container_name: orders-service
  # depends_on:
  #   orders-db:
  #     condition: service_healthy
  # environment:
  #   SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/ordersdb
  #   SPRING_DATASOURCE_USERNAME: yash
  #   SPRING_DATASOURCE_PASSWORD: yash123
  #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #   SERVER_PORT: 8082
  # ports:
  #   - "8082:8082"
  # restart: on-failure
  # networks:
  #   - eci-net

  # ---------- Payments ----------
  payments-db:
    image: postgres:15
    container_name: payments-db
    restart: always
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: yash123
    ports:
      - "5436:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data
      - ./init/payments:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yash -d paymentsdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - eci-net

  payments-service:
    build:
      context: ../payments-service
      dockerfile: Dockerfile
    container_name: payments-service
    depends_on:
      payments-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payments-db:5432/paymentsdb
      SPRING_DATASOURCE_USERNAME: yash
      SPRING_DATASOURCE_PASSWORD: yash123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    restart: on-failure
    volumes:
      - ./init/payments:/app/init/payments
    networks:
      - eci-net

networks:
  eci-net:
    driver: bridge

volumes:
  catalog_data:
  inventory_data:
  orders_data:
  payments_data:
